Blog/tools/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('Blog.tools',
    # Examples:
    # url(r'^$', 'Blog.views.home', name='home'),
)

Blog/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
     url(r'^', include('Blog.tools.urls'), {'SSL':True}),
     url(r'^', include('Blog.comments.urls'), {'SSL':True}),
     url(r'^', include('Blog.index.urls'), {'SSL':True}),
)

Blog/tools/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

class Note(models.Model):
  topic = models.CharField(unique=True, max_length=100)
  date_add = models.DateTimeField(auto_now=True)
  date_change = models.DateTimeField(null=True)
  note = models.TextField()
  
class Tag(models.Model):
  name = models.CharField(unique=True, max_length=32)
  
class Group(models.Model):
  note = models.ForeignKey('Note', null=False, blank=False)
  tag = models.ForeignKey('Tag', null=True, blank=False)
  author = models.ForeignKey(User)
  
class Var(models.Model):
  name = models.CharField(max_length=100)
  var = models.CharField(max_length=100)
  

Blog/tools/views.py
#-*- coding: utf-8 -*-
from django.shortcuts import render
from django.views.generic.base import View
from django.core.paginator import Paginator
from django.http import Http404

class BaseView(View):
  template_name=None
  model=None
  view_data={}
  where={}
  order_by=[]
  back_url=None
  item_for_page=None
  page_view=None
  default_page_number=None
  footer_value=None
    
  def get(self, request, *args, **kwargs):
    page = None
    if 'page' in kwargs and kwargs['page'] != u'':
      page = int(kwargs['page'])
    data=[]
    if self.model and self.model is not None:
      try:
        order_by=[]
        if 'sort' in kwargs and kwargs['sort']!='':
          order_by.append(kwargs['sort'])
        if 'where' in kwargs and kwargs['where']!='':
          self.where.update(kwargs['where'])
        if len(self.order_by)>0:
          order_by.extend(self.order_by)
        if len(self.where)>0 and len(order_by)>0:
          data = self.model.objects.filter(**self.where).order_by(*order_by)
        elif len(self.where)>0:
          data = self.model.objects.filter(**self.where)
        elif len(order_by)>0:
          data = self.model.objects.all().order_by(*order_by)
        else:
          data = self.model.objects.all()
      except:
        return render(request, 'info.html', {'back_url':self.back_url, 'errors':[_(u'Błąd w klasie BaseView.'), ]})
    paginator = Paginator(data, self.item_for_page)
    if page and paginator.num_pages >= page:
      data = paginator.page(page)
    elif paginator.num_pages >= self.default_page_number:
      data = paginator.page(self.default_page_number)
    else:
      raise Http404()
    self.view_data.update({'page':page, 'paginator':paginator, 'data':data, 'page_view':self.page_view, 'footer_value':self.footer_value,'request':request})
    

Blog/tools/templates/author.html
{{ author }}

Blog/tools/templates/base.html
<!DOCTYPE html>
{% load bootstrap3 staticfiles i18n %}
{% load url from future %}
<html lang="pl">
  <head>
		<meta charset="UTF-8">
  	<title>{% block title %}Blog Damian Giebas{% endblock %}</title>
  	<!-- CSS Bootstrap -->
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
    
		<!-- JS Bootstrap i jQuery -->
    {% bootstrap_javascript jquery=True %}
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>

		{% block head %}
		{% endblock %}
	</head>
  <body>
    {% include 'panel.html' %}
	  <div class="container">
		  <div class="row">
		  	<div class="col-md-10">
			    {% block content %}
			    {% endblock %}
		    </div>
	      {% include 'menu.html' %}
		    
		  </div>
	  </div>
        
   <div class="panel panel-footer"><small>{{ footer_value }}</small></div>
  </body>
</html>

Blog/tools/templates/delete.html
{% extends "base.html" %}
{% load bootstrap3 i18n %}

	{% block content %}
		<form action="" method="post">
			{% csrf_token %}
			<div class="alert alert-block">
				{% trans 'Do you really want delete this item?' %}
			</div>
			<input type="submit" 
		       value="{% trans 'Delete' %}"
		       class="btn btn-warning"
		       />
		</form> 
	{% endblock %}

Blog/tools/templates/info.html
{% extends "base.html" %}
{% load bootstrap3 i18n %}
	{% block head %}
	{% endblock %}

	{% block content %}
		{% if errors %}
			{% for error in errors %}
				<div class="alert alert-error">
					{{ error }}
				</div>
			{% endfor %}
		{% endif %}
		
		{% if warnings %}
			{% for warning in warnings %}
				<div class="alert alert-block">
					{{ warning }}
				</div>
			{% endfor %}
		{% endif %}
		
		{% if infos %}
			{% for info in infos %}
				<div class="alert alert-info">
					{{ info }}
				</div>
			{% endfor %}
		{% endif %}
		
		{% if successes %}
			{% for success in successes %}
				<div class="alert alert-success">
					{{ success }}
				</div>
			{% endfor %}
		{% endif %}
		
		{% if back_url %}
			<p>
				<a href="{%url back_url %}" class="btn">{% trans 'Powrót' %}</a>
			</p>
		{% endif %}
		
	{% endblock %}

Blog/tools/templates/menu.html
{% load bootstrap3 i18n %}
{% load url from future %}
<div class="col-md-2">
	<div class="panel panel-default">
		  {% if request.user.is_authenticated %}
		   <div class="panel-heading">{{ request.user.username }}</div>
		   <div class="panel-body">
		   <ul class="nav">
		     {% if perms.user.add_note %}<li><small><a href="{% url 'news/add' %}">Dodaj newsa</a></small></li>{% endif %}
		   </ul>
		   </div>
		  {% else %}
		   <div class="panel-heading">{% trans 'Niezalogowany' %}</div>
		  {% endif %}
	 {% block menu %}
	 {% endblock %}
	</div>
</div>

Blog/tools/templates/pagination.html
{% load i18n %}
{% block paginationblock %}
		<ul class="pagination pagination-centered">
			<li {% if not data.has_previous %}class="disabled"{% endif %}><a href="{% if data.has_previous %}{% url page_view data.previous_page_number %}{% endif %}">{% trans 'Prev' %}</a></li>
				{% for page_number in paginator.page_range %}
					<li {% if page_number == page or page_number == 1 and not page %} class="active" {% endif %} ><a href="{% url page_view page_number %}">{{ page_number }}</a></li>
				{% endfor %}		
			<li {% if not data.has_next %}class="disabled" {% endif %}><a href="{% if data.has_next %}{% url page_view data.next_page_number %}{% endif %}">{% trans 'Next' %}</a></li>
		</ul>
{% endblock %}

Blog/tools/templates/panel.html
{% load bootstrap3 i18n %}
{% load url from future %}
  {% block panel %}

  <nav class="navbar navbar-default" role="navigation">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li {% if "index" in request.path %} class="active" {% endif %} {% ifequal request.path "/" %} class="active" {% endifequal %}>
            <a href="{% url 'index' %}">{% trans "Index" %}</a>
          </li>
          {% if request.user.is_authenticated %}
            <li {% if "logout" in request.path %} class="active" {% endif %}>
              <a href="{% url 'logout' %}">{% trans "Wyloguj" %}</a>
            </li>
          {% else %}
            <li {% if "login" in request.path %} class="active" {% endif %}>
              <a href="{% url 'login' %}">{% trans "Zaloguj" %}</a>
            </li>
          {% endif %}
        </ul>
      </div>
   </nav>
  {% endblock %}

Blog/tools/templates/tags.html
{% load base64f %}
{% for tag in tagslist %}
  <strong><small><a href="{% url 'news/show/by/tag' tag|base64f %}">{{ tag }}</a></small></strong>
{% endfor %}