Blog/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
     url(r'^', include('Blog.tools.urls'), {'SSL':True}),
     url(r'^', include('Blog.comments.urls'), {'SSL':True}),
     url(r'^', include('Blog.index.urls'), {'SSL':True}),
)

Blog/comments/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.core.validators import RegexValidator
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from Blog.tools.models import Note

class Comments(models.Model):
  logged_user = models.ForeignKey(User, null=True)
  not_logged_user = models.CharField(max_length=30, null=True, validators=[RegexValidator(regex='^.{3,30}$', message=_(u'Nazwa musi posiadać przynajmniej 3 znaki i maksymalnie 30'), code='nomatch')])
  note = models.ForeignKey(Note, null=False, blank=False)
  comment = models.TextField()
  date_add = models.DateTimeField(auto_now=True)
  date_change = models.DateTimeField(auto_created=True, null=True)
  
class CommentsReply(models.Model):
  comment = models.ForeignKey('Comments', null=False, blank=False, related_name='base_comment')
  reply = models.ForeignKey('Comments', null=False, blank=False, related_name='reply')

Blog/index/templates/add_news.html
{% extends "base.html" %}
{% load bootstrap3 i18n %}
  {% block content %}
    <form method="post" action="" class="form-horizontal offset2" name="form" >
	    {% csrf_token %}
	    {% bootstrap_form form layout="horizontal" %}
      <div class="form-group">
        <div class="col-md-6 control-label">
	       <label>{% trans 'Proszę podać maksymalnie 5 tagów oddzielając je średnikiem.'%}</label>
	      </div>
	    </div>
	    {% bootstrap_form tagform layout="horizontal" %}
      {% buttons layout='horizontal' %}
	        <button class="btn btn-default btn-primary">{% trans 'Zapisz' %}</button>
	        {% if 'news/edit' in request.path %}
	         <a href="{% url 'news/show' pk %}" class="btn btn-default">{% trans 'Powrót' %}</a>
	        {% else %}
	         <a href="{% url 'index' %}" class="btn btn-default">{% trans 'Powrót' %}</a>
	        {% endif %}
      {% endbuttons %}
    </form>
  
  {% endblock %}

Blog/index/templates/delete_comment.html
{% extends "base.html" %}
{% load bootstrap3 i18n %}
  {% block content %}
    <form method="post" action="" class="form-horizontal" name="form" >
      {% csrf_token %}
      <div class="form-group alert alert-danger">
         <label>{% trans 'Czy napewno chcesz usunąć komentarz?'%}</label>
      </div>
      {% buttons %}
        <button class="btn btn-default btn-warning">{% trans 'Usuń' %}</button>
        <a href="{{ back_url }}" class="btn btn-default">{% trans 'Powrót' %}</a>
      {% endbuttons %}
    </form>
  
  {% endblock %}

Blog/index/templates/delete_news.html
{% extends "base.html" %}
{% load bootstrap3 i18n %}
  {% block content %}
    <form method="post" action="" class="form-horizontal" name="form" >
      {% csrf_token %}
      <div class="form-group alert alert-danger">
         <label>{% trans 'Czy napewno chcesz usunąć wpis?'%}</label>
      </div>
      {% buttons %}
        <button class="btn btn-default btn-warning">{% trans 'Usuń' %}</button>
        <a href="{% url 'news/show' pk %}" class="btn btn-default">{% trans 'Powrót' %}</a>
      {% endbuttons %}
    </form>
  
  {% endblock %}

Blog/index/templates/edit_comment.html
{% extends "base.html" %}
  {% load tags author i18n bootstrap3 %}
  {% block content %}
      <form class="form" action="" method="POST" name="form">
        {% csrf_token %}
        <div class="form-group">
          <label>{% trans 'Użytkownik' %}</label>
          <input class="form-control" disabled="True" id="id_logged_user" maxlength="30" name="call_number" type="text" value="{% if comment.logged_user %}{{ comment.logged_user }}{% else %}{{ comment.not_logged_user }}{% endif %}">
        </div>
        
      {% bootstrap_form comments_form %}
      {% buttons %}
          <button class="btn btn-default btn-primary">{% trans 'Zapisz komentarz' %}</button>
          <a href="{{ back_url }}" class="btn btn-default">{% trans 'Powrót' %}</a>
          
      {% endbuttons %}
      </form>
  {% endblock %}

Blog/index/templates/index.html
{% extends "base.html" %}
  {% load tags author i18n %}
	{% block content %}
  {% if data %}
		{% for news in data %}
		 {% if forloop.first %}
		   <div class="panel panel-default">
		     <div class="panel-heading"><h2><a href="{% url 'news/show' news.pk %}" class="btn-link">{{ news.topic|title }}</a></h2></div>
		 {% else %}
		   <div class="panel panel-default">
		     <div class="panel-heading"><h3><a href="{% url 'news/show' news.pk %}" class="btn-link">{{ news.topic|title }}</a></h3></div>
		 {% endif %}
		       <div class="panel-body">{{ news.note|linebreaksbr|truncatewords_html:15 }}</div>
           <div class="panel-footer">
             <small><strong>{{ news.date_add }}</strong> {% trans 'przez' %} <strong>{% author news %}</strong></small>
             <div>{% tags news %}</div>
           </div>
       </div>
		{% endfor %}
		
    {% endif %}
		{% include 'pagination.html' %}
	{% endblock %}

Blog/index/templates/login.html
{% extends "base.html" %}
{% load bootstrap3 i18n %}
  {% block content%}
  <form class="form-horizontal" name="form" action="" method="post">
    {% csrf_token %}
    {% if login_failed %}<p class="text-error">{% trans "Niepoprawny login lub/i hasło" %}</p>{% endif %}
    {% bootstrap_form form layout="horizontal" %}
    {% buttons layout="horizontal" %}
        <button class="btn btn-default btn-primary">{% trans 'Zaloguj' %}</button>
        <a href="{% url 'index' %}" class="btn btn-default">{% trans 'Powrót' %}</a>
    {% endbuttons %}
  </form>
  {% endblock %}

Blog/index/templates/reply_add.html
{% extends "base.html" %}
  {% load tags author i18n bootstrap3 %}
  {% block content %}
      <form class="form" action="" method="POST" name="form">
        {% csrf_token %}
        {% if request.user.is_authenticated %}
          <div class="form-group">
            <label>{% trans 'Użytkownik' %}</label>
            <input class="form-control" disabled="True" id="id_logged_user" maxlength="30" name="call_number" type="text" value="{{ request.user.username }}">
          </div>
        {% endif %}
        
      {% bootstrap_form comments_form %}
      {% buttons %}
          <button class="btn btn-default btn-primary">{% trans 'Dodaj komentarz' %}</button>
          <a href="{{ back_url }}" class="btn btn-default">{% trans 'Powrót' %}</a>
      {% endbuttons %}
      </form>
  {% endblock %}

Blog/index/templates/show_news.html
{% extends "base.html" %}
  {% load tags author i18n bootstrap3 %}
  {% block content %}
	 <div class="panel panel-default">
	   <div class="panel-heading"><h2 class="text-info">{{ news.topic|title }}</h2></div>
     <div class="panel-body">{{ news.note|linebreaksbr }}</div>
     <div class="panel-footer">
      <div class="pull-left">
        <small><strong>{{ news.date_add }}</strong> {% trans 'przez' %} <strong>{% author news %}</strong></small>
      </div>
      <div class="pull-right">
        <small><strong><a class="btn-link" href="{% url 'news/delete' news.pk %}">{% trans 'Usuń' %}</a> <a class="btn-link" href="{% url 'news/edit' news.pk %}">{% trans 'Edytuj' %}</a></strong></small>
      </div>
      <br class="clear"/>
      <div>{% tags news %}</div>
     </div>
     </div>
    
    <br class="clear" />
    {% if comments %}
    
	  <div class="panel panel-default">
	    <div class="panel-heading">
	     {% trans 'Komentarze' %}
	    </div>
      <div class="panel-body">
        {% include 'comments.html' %}
      </div>
    </div>
    {% endif %}
	    <form class="form" action="" method="POST" name="form">
	      {% csrf_token %}
	      {% if request.user.is_authenticated %}
	        <div class="form-group">
	          <label>{% trans 'Użytkownik' %}</label>
		        <input class="form-control" disabled="True" id="id_logged_user" maxlength="30" name="call_number" type="text" value="{{ request.user.username }}">
		      </div>
		    {% endif %}
	      
      {% bootstrap_form comments_form %}
      {% buttons %}
	        <button class="btn btn-default btn-primary">{% trans 'Dodaj komentarz' %}</button>
	    {% endbuttons %}
	    </form>
  {% endblock %}